export const PLAY_SELECTORS = [
  '.vjs-big-play-button',
  'button[aria-label="Play"]',
  'button[aria-label*="play" i]',
  '.jw-icon-display',
  '.plyr__control--overlaid',
  '.ytp-large-play-button',
  '.play-button',
  '[class*="play" i][class*="btn" i]',
  'video',
];

export const SERVER_SELECTORS = [
  '.server-item',
  '.server-item a',
  '.server-item button',
  '.list-server a',
  '.list-server button',
  '.server-list button',
  '.server-list a',
  '.server a',
  '.servers a',
  '.servers button',
  '[class*="server"] button',
  '[class*="server"] a',
  '[class*="stream"] button',
  '[class*="stream"] a',
  '[data-server] a',
  '.nav-tabs a',
  '.nav-tabs button',
  '.tab-server li',
  '[role="tab"]',
  '[data-toggle="tab"]',
  '[data-server]',
];

export const LISTING_ITEM_SELECTORS = [
  'a[href*="/truc-tiep/"]',
  'a[href*="-vs-"]',
  '.match-hot-card-container a[href]',
  '.match-super-hot-card-container a[href]',
  '.live-match a[href]',
  '.hot-match a[href]',
  '[class*="match" i] a[href]',
  'a[aria-label][href^="/"]',
  'a[href*="match"]',
  'a[href*="live"]',
  'a[href*="watch"]',
  'a[href*="truc-tiep"]',
  'a[href*="xem"]',
  '.match-item a',
  '.event-item a',
  'li a',
];
